### ISSUE TITLE
how to connect iphone app to TV

### ISSUE THREAD

**Issue by wamobile** [D-32/Snap#1]
I have you iOS app on iPhone 6 and 5s and TV app on Simulator .
Can we connect on simulator ?.can you please tell me how to do so  ?or whats the solution to test the connection ?

**Comment by D-32** [comment]
Damn, you're fast! Sadly I didn't manage to run the iOS app & tvOS app at the same time. So I'm currently waiting to get my USB-C cable to run the app on the actual device.
All the networking code is untested...
