### ISSUE TITLE
Linker issue with Async Framework

### ISSUE THREAD

**Issue by wamobile** [D-32/Snap#2]
Hey , I am troubling you again , I am trying to archive and it says the following error for TVOS.Can you please help.
ld: building for tvOS, but linking against dylib built for iOS, file '/Users/***********/Libs/AsyncNetworkIOS.framework/AsyncNetworkIOS' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by D-32** [comment]
My cable arrived so I'll probably try tonight myself :)

**Comment by D-32** [comment]
@wamobile Why are you actually trying to archive it?

**Comment by wamobile** [comment]
hey it worked even on simulator ,Downloaded Asysnc Files from somewhere else.Thanks anyway .

**Comment by D-32** [comment]
You managed to run it on the actual device?

**Comment by wamobile** [comment]
yeah ,i did write up on my own , but thanks for the framework this was really helpful.
